// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/jackc/pgtype"
)

const assignRoleByCode = `-- name: AssignRoleByCode :one
INSERT INTO user_roles (
    id,
    user_id,
    role_id,
    assigned_by,
    assigned_at,
    expires_at,
    created_at
)
SELECT
    $1,
    $2,
    r.id,
    $4,
    $5,
    NULL,
    $6
FROM auth_roles r
WHERE r.code = $3
    AND r.enabled = TRUE
ON CONFLICT (user_id, role_id) DO UPDATE
SET assigned_by = EXCLUDED.assigned_by
RETURNING
    id,
    user_id,
    role_id,
    assigned_by,
    assigned_at,
    expires_at,
    created_at
`

type AssignRoleByCodeParams struct {
	ID         string         `db:"id" json:"id"`
	UserID     string         `db:"user_id" json:"user_id"`
	Code       string         `db:"code" json:"code"`
	AssignedBy sql.NullString `db:"assigned_by" json:"assigned_by"`
	AssignedAt time.Time      `db:"assigned_at" json:"assigned_at"`
	CreatedAt  time.Time      `db:"created_at" json:"created_at"`
}

func (q *Queries) AssignRoleByCode(ctx context.Context, arg AssignRoleByCodeParams) (UserRole, error) {
	row := q.db.QueryRow(ctx, assignRoleByCode,
		arg.ID,
		arg.UserID,
		arg.Code,
		arg.AssignedBy,
		arg.AssignedAt,
		arg.CreatedAt,
	)
	var i UserRole
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoleID,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createCredential = `-- name: CreateCredential :one
INSERT INTO auth_credentials (
    id,
    user_id,
    credential_type,
    password_hash,
    password_hash_alg,
    password_hash_params_version,
    password_hash_params_json,
    password_changed_at,
    password_expires_at,
    failed_attempt_count,
    last_failed_at,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7::jsonb, $8, $9, 0, NULL, $10, $11)
RETURNING
    id,
    user_id,
    credential_type,
    password_hash,
    password_hash_alg,
    password_hash_params_version,
    password_hash_params_json,
    password_changed_at,
    password_expires_at,
    failed_attempt_count,
    last_failed_at,
    created_at,
    updated_at
`

type CreateCredentialParams struct {
	ID                        string       `db:"id" json:"id"`
	UserID                    string       `db:"user_id" json:"user_id"`
	CredentialType            string       `db:"credential_type" json:"credential_type"`
	PasswordHash              string       `db:"password_hash" json:"password_hash"`
	PasswordHashAlg           string       `db:"password_hash_alg" json:"password_hash_alg"`
	PasswordHashParamsVersion string       `db:"password_hash_params_version" json:"password_hash_params_version"`
	Column7                   pgtype.JSONB `db:"column_7" json:"column_7"`
	PasswordChangedAt         time.Time    `db:"password_changed_at" json:"password_changed_at"`
	PasswordExpiresAt         sql.NullTime `db:"password_expires_at" json:"password_expires_at"`
	CreatedAt                 time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt                 time.Time    `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (AuthCredential, error) {
	row := q.db.QueryRow(ctx, createCredential,
		arg.ID,
		arg.UserID,
		arg.CredentialType,
		arg.PasswordHash,
		arg.PasswordHashAlg,
		arg.PasswordHashParamsVersion,
		arg.Column7,
		arg.PasswordChangedAt,
		arg.PasswordExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i AuthCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialType,
		&i.PasswordHash,
		&i.PasswordHashAlg,
		&i.PasswordHashParamsVersion,
		&i.PasswordHashParamsJson,
		&i.PasswordChangedAt,
		&i.PasswordExpiresAt,
		&i.FailedAttemptCount,
		&i.LastFailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSecurityEvent = `-- name: CreateSecurityEvent :exec
INSERT INTO auth_security_events (
    id,
    event_type,
    user_id,
    session_id,
    username_snapshot,
    request_id,
    client_ip,
    user_agent,
    caller_service,
    status,
    reason_code,
    metadata_json,
    created_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12::jsonb, $13)
`

type CreateSecurityEventParams struct {
	ID               string         `db:"id" json:"id"`
	EventType        string         `db:"event_type" json:"event_type"`
	UserID           sql.NullString `db:"user_id" json:"user_id"`
	SessionID        sql.NullString `db:"session_id" json:"session_id"`
	UsernameSnapshot sql.NullString `db:"username_snapshot" json:"username_snapshot"`
	RequestID        sql.NullString `db:"request_id" json:"request_id"`
	ClientIp         sql.NullString `db:"client_ip" json:"client_ip"`
	UserAgent        sql.NullString `db:"user_agent" json:"user_agent"`
	CallerService    sql.NullString `db:"caller_service" json:"caller_service"`
	Status           string         `db:"status" json:"status"`
	ReasonCode       sql.NullString `db:"reason_code" json:"reason_code"`
	Column12         pgtype.JSONB   `db:"column_12" json:"column_12"`
	CreatedAt        time.Time      `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateSecurityEvent(ctx context.Context, arg CreateSecurityEventParams) error {
	_, err := q.db.Exec(ctx, createSecurityEvent,
		arg.ID,
		arg.EventType,
		arg.UserID,
		arg.SessionID,
		arg.UsernameSnapshot,
		arg.RequestID,
		arg.ClientIp,
		arg.UserAgent,
		arg.CallerService,
		arg.Status,
		arg.ReasonCode,
		arg.Column12,
		arg.CreatedAt,
	)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO auth_sessions (
    id,
    user_id,
    access_token_hash,
    access_token_hash_alg,
    access_token_hash_key_version,
    token_type,
    status,
    issued_at,
    expires_at,
    last_seen_at,
    revoked_at,
    revoke_reason,
    client_ip,
    user_agent,
    created_request_id,
    revoked_request_id,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, 'Bearer', 'active', $6, $7, NULL, NULL, NULL, $8, $9, $10, NULL, $11, $12)
RETURNING
    id,
    user_id,
    access_token_hash,
    access_token_hash_alg,
    access_token_hash_key_version,
    token_type,
    status,
    issued_at,
    expires_at,
    last_seen_at,
    revoked_at,
    revoke_reason,
    client_ip,
    user_agent,
    created_request_id,
    revoked_request_id,
    created_at,
    updated_at
`

type CreateSessionParams struct {
	ID                        string         `db:"id" json:"id"`
	UserID                    string         `db:"user_id" json:"user_id"`
	AccessTokenHash           string         `db:"access_token_hash" json:"access_token_hash"`
	AccessTokenHashAlg        string         `db:"access_token_hash_alg" json:"access_token_hash_alg"`
	AccessTokenHashKeyVersion string         `db:"access_token_hash_key_version" json:"access_token_hash_key_version"`
	IssuedAt                  time.Time      `db:"issued_at" json:"issued_at"`
	ExpiresAt                 time.Time      `db:"expires_at" json:"expires_at"`
	ClientIp                  sql.NullString `db:"client_ip" json:"client_ip"`
	UserAgent                 sql.NullString `db:"user_agent" json:"user_agent"`
	CreatedRequestID          sql.NullString `db:"created_request_id" json:"created_request_id"`
	CreatedAt                 time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt                 time.Time      `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.AccessTokenHash,
		arg.AccessTokenHashAlg,
		arg.AccessTokenHashKeyVersion,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.ClientIp,
		arg.UserAgent,
		arg.CreatedRequestID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessTokenHash,
		&i.AccessTokenHashAlg,
		&i.AccessTokenHashKeyVersion,
		&i.TokenType,
		&i.Status,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.ClientIp,
		&i.UserAgent,
		&i.CreatedRequestID,
		&i.RevokedRequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSessionRevocation = `-- name: CreateSessionRevocation :exec
INSERT INTO session_revocations (
    id,
    session_id,
    user_id,
    reason,
    revoked_by,
    request_id,
    revoked_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (session_id) DO NOTHING
`

type CreateSessionRevocationParams struct {
	ID        string         `db:"id" json:"id"`
	SessionID string         `db:"session_id" json:"session_id"`
	UserID    string         `db:"user_id" json:"user_id"`
	Reason    string         `db:"reason" json:"reason"`
	RevokedBy sql.NullString `db:"revoked_by" json:"revoked_by"`
	RequestID sql.NullString `db:"request_id" json:"request_id"`
	RevokedAt time.Time      `db:"revoked_at" json:"revoked_at"`
}

func (q *Queries) CreateSessionRevocation(ctx context.Context, arg CreateSessionRevocationParams) error {
	_, err := q.db.Exec(ctx, createSessionRevocation,
		arg.ID,
		arg.SessionID,
		arg.UserID,
		arg.Reason,
		arg.RevokedBy,
		arg.RequestID,
		arg.RevokedAt,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO auth_users (
    id,
    username,
    display_name,
    email,
    phone,
    status,
    locked_until,
    last_login_at,
    created_at,
    updated_at,
    deleted_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NULL)
RETURNING
    id,
    username,
    display_name,
    email,
    phone,
    status,
    locked_until,
    last_login_at,
    created_at,
    updated_at,
    deleted_at
`

type CreateUserParams struct {
	ID          string         `db:"id" json:"id"`
	Username    string         `db:"username" json:"username"`
	DisplayName string         `db:"display_name" json:"display_name"`
	Email       sql.NullString `db:"email" json:"email"`
	Phone       sql.NullString `db:"phone" json:"phone"`
	Status      string         `db:"status" json:"status"`
	LockedUntil sql.NullTime   `db:"locked_until" json:"locked_until"`
	LastLoginAt sql.NullTime   `db:"last_login_at" json:"last_login_at"`
	CreatedAt   time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time      `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.DisplayName,
		arg.Email,
		arg.Phone,
		arg.Status,
		arg.LockedUntil,
		arg.LastLoginAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActiveSessionByTokenHash = `-- name: GetActiveSessionByTokenHash :one
SELECT
    s.id,
    s.user_id,
    s.access_token_hash,
    s.access_token_hash_alg,
    s.access_token_hash_key_version,
    s.token_type,
    s.status,
    s.issued_at,
    s.expires_at,
    s.last_seen_at,
    s.revoked_at,
    s.revoke_reason,
    s.client_ip,
    s.user_agent,
    s.created_request_id,
    s.revoked_request_id,
    s.created_at,
    s.updated_at
FROM auth_sessions s
WHERE s.access_token_hash = $1
    AND s.status = 'active'
    AND s.expires_at > now()
`

func (q *Queries) GetActiveSessionByTokenHash(ctx context.Context, accessTokenHash string) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByTokenHash, accessTokenHash)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessTokenHash,
		&i.AccessTokenHashAlg,
		&i.AccessTokenHashKeyVersion,
		&i.TokenType,
		&i.Status,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.ClientIp,
		&i.UserAgent,
		&i.CreatedRequestID,
		&i.RevokedRequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCredentialByUserID = `-- name: GetCredentialByUserID :one
SELECT
    id,
    user_id,
    credential_type,
    password_hash,
    password_hash_alg,
    password_hash_params_version,
    password_hash_params_json,
    password_changed_at,
    password_expires_at,
    failed_attempt_count,
    last_failed_at,
    created_at,
    updated_at
FROM auth_credentials
WHERE user_id = $1
    AND credential_type = $2
`

type GetCredentialByUserIDParams struct {
	UserID         string `db:"user_id" json:"user_id"`
	CredentialType string `db:"credential_type" json:"credential_type"`
}

func (q *Queries) GetCredentialByUserID(ctx context.Context, arg GetCredentialByUserIDParams) (AuthCredential, error) {
	row := q.db.QueryRow(ctx, getCredentialByUserID, arg.UserID, arg.CredentialType)
	var i AuthCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialType,
		&i.PasswordHash,
		&i.PasswordHashAlg,
		&i.PasswordHashParamsVersion,
		&i.PasswordHashParamsJson,
		&i.PasswordChangedAt,
		&i.PasswordExpiresAt,
		&i.FailedAttemptCount,
		&i.LastFailedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT
    s.id,
    s.user_id,
    s.access_token_hash,
    s.access_token_hash_alg,
    s.access_token_hash_key_version,
    s.token_type,
    s.status,
    s.issued_at,
    s.expires_at,
    s.last_seen_at,
    s.revoked_at,
    s.revoke_reason,
    s.client_ip,
    s.user_agent,
    s.created_request_id,
    s.revoked_request_id,
    s.created_at,
    s.updated_at
FROM auth_sessions s
WHERE s.id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessTokenHash,
		&i.AccessTokenHashAlg,
		&i.AccessTokenHashKeyVersion,
		&i.TokenType,
		&i.Status,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.ClientIp,
		&i.UserAgent,
		&i.CreatedRequestID,
		&i.RevokedRequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    username,
    display_name,
    email,
    phone,
    status,
    locked_until,
    last_login_at,
    created_at,
    updated_at,
    deleted_at
FROM auth_users
WHERE id = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT
    id,
    username,
    display_name,
    email,
    phone,
    status,
    locked_until,
    last_login_at,
    created_at,
    updated_at,
    deleted_at
FROM auth_users
WHERE username = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPermissionCodesByUserID = `-- name: ListPermissionCodesByUserID :many
SELECT DISTINCT
    p.code
FROM user_roles ur
INNER JOIN auth_roles r
    ON r.id = ur.role_id
INNER JOIN role_permissions rp
    ON rp.role_id = r.id
INNER JOIN auth_permissions p
    ON p.id = rp.permission_id
WHERE ur.user_id = $1
    AND r.enabled = TRUE
    AND p.enabled = TRUE
    AND (ur.expires_at IS NULL OR ur.expires_at > now())
ORDER BY p.code ASC
`

func (q *Queries) ListPermissionCodesByUserID(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listPermissionCodesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleCodesByUserID = `-- name: ListRoleCodesByUserID :many
SELECT
    r.code
FROM user_roles ur
INNER JOIN auth_roles r
    ON r.id = ur.role_id
WHERE ur.user_id = $1
    AND r.enabled = TRUE
    AND (ur.expires_at IS NULL OR ur.expires_at > now())
ORDER BY r.code ASC
`

func (q *Queries) ListRoleCodesByUserID(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listRoleCodesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :one
UPDATE auth_sessions
SET status = 'revoked',
    revoked_at = $2,
    revoke_reason = $3,
    revoked_request_id = $4,
    updated_at = $2
WHERE id = $1
    AND status = 'active'
RETURNING
    id,
    user_id,
    access_token_hash,
    access_token_hash_alg,
    access_token_hash_key_version,
    token_type,
    status,
    issued_at,
    expires_at,
    last_seen_at,
    revoked_at,
    revoke_reason,
    client_ip,
    user_agent,
    created_request_id,
    revoked_request_id,
    created_at,
    updated_at
`

type RevokeSessionParams struct {
	ID               string         `db:"id" json:"id"`
	RevokedAt        sql.NullTime   `db:"revoked_at" json:"revoked_at"`
	RevokeReason     sql.NullString `db:"revoke_reason" json:"revoke_reason"`
	RevokedRequestID sql.NullString `db:"revoked_request_id" json:"revoked_request_id"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, revokeSession,
		arg.ID,
		arg.RevokedAt,
		arg.RevokeReason,
		arg.RevokedRequestID,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessTokenHash,
		&i.AccessTokenHashAlg,
		&i.AccessTokenHashKeyVersion,
		&i.TokenType,
		&i.Status,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.ClientIp,
		&i.UserAgent,
		&i.CreatedRequestID,
		&i.RevokedRequestID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserLastLoginAt = `-- name: UpdateUserLastLoginAt :exec
UPDATE auth_users
SET last_login_at = $2,
    updated_at = $2
WHERE id = $1
    AND deleted_at IS NULL
`

type UpdateUserLastLoginAtParams struct {
	ID          string       `db:"id" json:"id"`
	LastLoginAt sql.NullTime `db:"last_login_at" json:"last_login_at"`
}

func (q *Queries) UpdateUserLastLoginAt(ctx context.Context, arg UpdateUserLastLoginAtParams) error {
	_, err := q.db.Exec(ctx, updateUserLastLoginAt, arg.ID, arg.LastLoginAt)
	return err
}
