// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"time"

	"github.com/jackc/pgtype"
)

type AuthCredential struct {
	ID                        string       `db:"id" json:"id"`
	UserID                    string       `db:"user_id" json:"user_id"`
	CredentialType            string       `db:"credential_type" json:"credential_type"`
	PasswordHash              string       `db:"password_hash" json:"password_hash"`
	PasswordHashAlg           string       `db:"password_hash_alg" json:"password_hash_alg"`
	PasswordHashParamsVersion string       `db:"password_hash_params_version" json:"password_hash_params_version"`
	PasswordHashParamsJson    pgtype.JSONB `db:"password_hash_params_json" json:"password_hash_params_json"`
	PasswordChangedAt         time.Time    `db:"password_changed_at" json:"password_changed_at"`
	PasswordExpiresAt         sql.NullTime `db:"password_expires_at" json:"password_expires_at"`
	FailedAttemptCount        int32        `db:"failed_attempt_count" json:"failed_attempt_count"`
	LastFailedAt              sql.NullTime `db:"last_failed_at" json:"last_failed_at"`
	CreatedAt                 time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt                 time.Time    `db:"updated_at" json:"updated_at"`
}

type AuthPermission struct {
	ID          string    `db:"id" json:"id"`
	Code        string    `db:"code" json:"code"`
	Domain      string    `db:"domain" json:"domain"`
	Action      string    `db:"action" json:"action"`
	Description string    `db:"description" json:"description"`
	Enabled     bool      `db:"enabled" json:"enabled"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
}

type AuthRole struct {
	ID          string    `db:"id" json:"id"`
	Code        string    `db:"code" json:"code"`
	Name        string    `db:"name" json:"name"`
	Description string    `db:"description" json:"description"`
	Enabled     bool      `db:"enabled" json:"enabled"`
	SystemRole  bool      `db:"system_role" json:"system_role"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
}

type AuthSecurityEvent struct {
	ID               string         `db:"id" json:"id"`
	EventType        string         `db:"event_type" json:"event_type"`
	UserID           sql.NullString `db:"user_id" json:"user_id"`
	SessionID        sql.NullString `db:"session_id" json:"session_id"`
	UsernameSnapshot sql.NullString `db:"username_snapshot" json:"username_snapshot"`
	RequestID        sql.NullString `db:"request_id" json:"request_id"`
	ClientIp         sql.NullString `db:"client_ip" json:"client_ip"`
	UserAgent        sql.NullString `db:"user_agent" json:"user_agent"`
	CallerService    sql.NullString `db:"caller_service" json:"caller_service"`
	Status           string         `db:"status" json:"status"`
	ReasonCode       sql.NullString `db:"reason_code" json:"reason_code"`
	MetadataJson     pgtype.JSONB   `db:"metadata_json" json:"metadata_json"`
	CreatedAt        time.Time      `db:"created_at" json:"created_at"`
}

type AuthSession struct {
	ID                        string         `db:"id" json:"id"`
	UserID                    string         `db:"user_id" json:"user_id"`
	AccessTokenHash           string         `db:"access_token_hash" json:"access_token_hash"`
	AccessTokenHashAlg        string         `db:"access_token_hash_alg" json:"access_token_hash_alg"`
	AccessTokenHashKeyVersion string         `db:"access_token_hash_key_version" json:"access_token_hash_key_version"`
	TokenType                 string         `db:"token_type" json:"token_type"`
	Status                    string         `db:"status" json:"status"`
	IssuedAt                  time.Time      `db:"issued_at" json:"issued_at"`
	ExpiresAt                 time.Time      `db:"expires_at" json:"expires_at"`
	LastSeenAt                sql.NullTime   `db:"last_seen_at" json:"last_seen_at"`
	RevokedAt                 sql.NullTime   `db:"revoked_at" json:"revoked_at"`
	RevokeReason              sql.NullString `db:"revoke_reason" json:"revoke_reason"`
	ClientIp                  sql.NullString `db:"client_ip" json:"client_ip"`
	UserAgent                 sql.NullString `db:"user_agent" json:"user_agent"`
	CreatedRequestID          sql.NullString `db:"created_request_id" json:"created_request_id"`
	RevokedRequestID          sql.NullString `db:"revoked_request_id" json:"revoked_request_id"`
	CreatedAt                 time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt                 time.Time      `db:"updated_at" json:"updated_at"`
}

type AuthUser struct {
	ID          string         `db:"id" json:"id"`
	Username    string         `db:"username" json:"username"`
	DisplayName string         `db:"display_name" json:"display_name"`
	Email       sql.NullString `db:"email" json:"email"`
	Phone       sql.NullString `db:"phone" json:"phone"`
	Status      string         `db:"status" json:"status"`
	LockedUntil sql.NullTime   `db:"locked_until" json:"locked_until"`
	LastLoginAt sql.NullTime   `db:"last_login_at" json:"last_login_at"`
	CreatedAt   time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time      `db:"updated_at" json:"updated_at"`
	DeletedAt   sql.NullTime   `db:"deleted_at" json:"deleted_at"`
}

type RolePermission struct {
	ID           string    `db:"id" json:"id"`
	RoleID       string    `db:"role_id" json:"role_id"`
	PermissionID string    `db:"permission_id" json:"permission_id"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
}

type SessionRevocation struct {
	ID        string         `db:"id" json:"id"`
	SessionID string         `db:"session_id" json:"session_id"`
	UserID    string         `db:"user_id" json:"user_id"`
	Reason    string         `db:"reason" json:"reason"`
	RevokedBy sql.NullString `db:"revoked_by" json:"revoked_by"`
	RequestID sql.NullString `db:"request_id" json:"request_id"`
	RevokedAt time.Time      `db:"revoked_at" json:"revoked_at"`
}

type UserRole struct {
	ID         string         `db:"id" json:"id"`
	UserID     string         `db:"user_id" json:"user_id"`
	RoleID     string         `db:"role_id" json:"role_id"`
	AssignedBy sql.NullString `db:"assigned_by" json:"assigned_by"`
	AssignedAt time.Time      `db:"assigned_at" json:"assigned_at"`
	ExpiresAt  sql.NullTime   `db:"expires_at" json:"expires_at"`
	CreatedAt  time.Time      `db:"created_at" json:"created_at"`
}
