\connect ai_gateway_system

INSERT INTO model_profiles (
    id,
    name,
    purpose,
    provider,
    base_url,
    model,
    enabled,
    is_default,
    timeout_ms,
    api_key_configured,
    supports_streaming,
    dimensions,
    top_n,
    default_parameters_json,
    credential_id,
    created_by_user_id,
    updated_by_user_id,
    created_at,
    updated_at
)
VALUES
    (
        'default-chat',
        'Local placeholder chat profile',
        'chat',
        'local_compatible',
        'http://host.docker.internal:11434/v1',
        'local-placeholder-chat',
        true,
        true,
        60000,
        true,
        true,
        null,
        null,
        '{"temperature":0.2}'::jsonb,
        'cred-local-chat',
        'usr_local_admin',
        'usr_local_admin',
        now(),
        now()
    ),
    (
        'default-embedding',
        'Local placeholder embedding profile',
        'embedding',
        'local_compatible',
        'http://host.docker.internal:11434/v1',
        'local-placeholder-embedding',
        true,
        true,
        60000,
        true,
        false,
        384,
        null,
        '{}'::jsonb,
        'cred-local-embedding',
        'usr_local_admin',
        'usr_local_admin',
        now(),
        now()
    ),
    (
        'default-rerank',
        'Local placeholder rerank profile',
        'rerank',
        'local_compatible',
        'http://host.docker.internal:11434/v1',
        'local-placeholder-rerank',
        true,
        true,
        60000,
        true,
        false,
        null,
        5,
        '{}'::jsonb,
        'cred-local-rerank',
        'usr_local_admin',
        'usr_local_admin',
        now(),
        now()
    )
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    provider = EXCLUDED.provider,
    base_url = EXCLUDED.base_url,
    model = EXCLUDED.model,
    enabled = EXCLUDED.enabled,
    is_default = EXCLUDED.is_default,
    timeout_ms = EXCLUDED.timeout_ms,
    api_key_configured = EXCLUDED.api_key_configured,
    supports_streaming = EXCLUDED.supports_streaming,
    dimensions = EXCLUDED.dimensions,
    top_n = EXCLUDED.top_n,
    default_parameters_json = EXCLUDED.default_parameters_json,
    credential_id = EXCLUDED.credential_id,
    updated_by_user_id = EXCLUDED.updated_by_user_id,
    updated_at = now();

INSERT INTO provider_credentials (
    id,
    profile_id,
    storage_mode,
    ciphertext,
    nonce,
    encryption_key_version,
    fingerprint_sha256,
    key_last4,
    status,
    created_by_user_id,
    created_at
)
VALUES
    (
        'cred-local-chat',
        'default-chat',
        'encrypted_column',
        decode('4e4a149baffbe76d4099cf2cb50789e077723d75d081d356f57ee7b22bffe6ff94608122d99c7b', 'hex'),
        decode('000102030405060708090a0b', 'hex'),
        'local-demo-key-v1',
        '01db0178d97656cc4638023b711d331d4c59cf16a35126e175d9b39bc9c2eb20',
        '-key',
        'active',
        'usr_local_admin',
        now()
    ),
    (
        'cred-local-embedding',
        'default-embedding',
        'encrypted_column',
        decode('68393da27a16ba4b40335506bfe832030f078211cd80d91855e564a06f8826f61c9600d3566cf1030be6f709', 'hex'),
        decode('101112131415161718191a1b', 'hex'),
        'local-demo-key-v1',
        '0414096c78c0e78770fec2d48abcb0f63efe39dbebf004721399574aa0cd6699',
        '-key',
        'active',
        'usr_local_admin',
        now()
    ),
    (
        'cred-local-rerank',
        'default-rerank',
        'encrypted_column',
        decode('e29e4525c3d48c0024cd7d378bbefd256d78e7dcfd89787b7c8d0be23fa8faef61993e3a0de4769660', 'hex'),
        decode('202122232425262728292a2b', 'hex'),
        'local-demo-key-v1',
        '02ac3f5104fd2d3ab39f8c3fb853076726633b2864077e43c96ebc9a9167057c',
        '-key',
        'active',
        'usr_local_admin',
        now()
    )
ON CONFLICT (id) DO UPDATE
SET ciphertext = EXCLUDED.ciphertext,
    nonce = EXCLUDED.nonce,
    encryption_key_version = EXCLUDED.encryption_key_version,
    fingerprint_sha256 = EXCLUDED.fingerprint_sha256,
    key_last4 = EXCLUDED.key_last4,
    status = EXCLUDED.status,
    deleted_at = null,
    disabled_at = null;
