// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: knowledge.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDocumentChunks = `-- name: CountDocumentChunks :one
SELECT COUNT(*)::bigint
FROM document_chunks dc
JOIN knowledge_documents d ON d.id = dc.document_id
JOIN knowledge_bases kb ON kb.id = d.knowledge_base_id
WHERE dc.document_id = $1
  AND d.deleted_at IS NULL
  AND kb.deleted_at IS NULL
  AND ($2::boolean OR d.created_by = $3 OR kb.created_by = $3)
`

type CountDocumentChunksParams struct {
	DocumentID string `json:"document_id"`
	CanReadAll bool   `json:"can_read_all"`
	UserID     string `json:"user_id"`
}

func (q *Queries) CountDocumentChunks(ctx context.Context, arg CountDocumentChunksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentChunks, arg.DocumentID, arg.CanReadAll, arg.UserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countDocumentsByKnowledgeBase = `-- name: CountDocumentsByKnowledgeBase :one
SELECT COUNT(*)::bigint
FROM knowledge_documents d
JOIN knowledge_bases kb ON kb.id = d.knowledge_base_id
WHERE d.knowledge_base_id = $1
  AND d.deleted_at IS NULL
  AND kb.deleted_at IS NULL
  AND ($2::boolean OR d.created_by = $3 OR kb.created_by = $3)
  AND ($4::text = '' OR d.status = $4)
`

type CountDocumentsByKnowledgeBaseParams struct {
	KnowledgeBaseID string `json:"knowledge_base_id"`
	CanReadAll      bool   `json:"can_read_all"`
	UserID          string `json:"user_id"`
	Status          string `json:"status"`
}

func (q *Queries) CountDocumentsByKnowledgeBase(ctx context.Context, arg CountDocumentsByKnowledgeBaseParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentsByKnowledgeBase,
		arg.KnowledgeBaseID,
		arg.CanReadAll,
		arg.UserID,
		arg.Status,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countKnowledgeBases = `-- name: CountKnowledgeBases :one
SELECT COUNT(*)::bigint
FROM knowledge_bases kb
WHERE kb.deleted_at IS NULL
  AND ($1::boolean OR kb.created_by = $2)
`

type CountKnowledgeBasesParams struct {
	CanReadAll bool   `json:"can_read_all"`
	UserID     string `json:"user_id"`
}

func (q *Queries) CountKnowledgeBases(ctx context.Context, arg CountKnowledgeBasesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countKnowledgeBases, arg.CanReadAll, arg.UserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countKnowledgeBasesGlobal = `-- name: CountKnowledgeBasesGlobal :one
SELECT COUNT(*)::bigint FROM knowledge_bases WHERE deleted_at IS NULL;
`

func (q *Queries) CountKnowledgeBasesGlobal(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countKnowledgeBasesGlobal)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countDocumentsGlobal = `-- name: CountDocumentsGlobal :one
SELECT COUNT(*)::bigint FROM knowledge_documents WHERE deleted_at IS NULL;
`

func (q *Queries) CountDocumentsGlobal(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentsGlobal)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO knowledge_documents (
  id,
  knowledge_base_id,
  file_ref,
  name,
  content_type,
  size_bytes,
  status,
  error_code,
  error_message,
  tags,
  parser_backend,
  current_job_id,
  created_by,
  created_at,
  updated_at
) VALUES (
  $1,
  $2,
  NULLIF($3, ''),
  $4,
  NULLIF($5, ''),
  $6,
  $7,
  NULL,
  NULL,
  $8,
  NULL,
  NULLIF($9, ''),
  $10,
  $11,
  $12
)
RETURNING
  id,
  knowledge_base_id,
  file_ref,
  name,
  content_type,
  size_bytes,
  status,
  error_code,
  error_message,
  0::bigint AS chunk_count,
  tags,
  parser_backend,
  current_job_id,
  created_by,
  created_at,
  updated_at,
  deleted_at
`

type CreateDocumentParams struct {
	ID              string             `json:"id"`
	KnowledgeBaseID string             `json:"knowledge_base_id"`
	FileRef         interface{}        `json:"file_ref"`
	Name            string             `json:"name"`
	ContentType     interface{}        `json:"content_type"`
	SizeBytes       pgtype.Int8        `json:"size_bytes"`
	Status          string             `json:"status"`
	Tags            []byte             `json:"tags"`
	CurrentJobID    interface{}        `json:"current_job_id"`
	CreatedBy       string             `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type CreateDocumentRow struct {
	ID              string             `json:"id"`
	KnowledgeBaseID string             `json:"knowledge_base_id"`
	FileRef         pgtype.Text        `json:"file_ref"`
	Name            string             `json:"name"`
	ContentType     pgtype.Text        `json:"content_type"`
	SizeBytes       pgtype.Int8        `json:"size_bytes"`
	Status          string             `json:"status"`
	ErrorCode       pgtype.Text        `json:"error_code"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	ChunkCount      int64              `json:"chunk_count"`
	Tags            []byte             `json:"tags"`
	ParserBackend   pgtype.Text        `json:"parser_backend"`
	CurrentJobID    pgtype.Text        `json:"current_job_id"`
	CreatedBy       string             `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (CreateDocumentRow, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.ID,
		arg.KnowledgeBaseID,
		arg.FileRef,
		arg.Name,
		arg.ContentType,
		arg.SizeBytes,
		arg.Status,
		arg.Tags,
		arg.CurrentJobID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateDocumentRow
	err := row.Scan(
		&i.ID,
		&i.KnowledgeBaseID,
		&i.FileRef,
		&i.Name,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.ChunkCount,
		&i.Tags,
		&i.ParserBackend,
		&i.CurrentJobID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createKnowledgeBase = `-- name: CreateKnowledgeBase :one
INSERT INTO knowledge_bases (
  id,
  name,
  description,
  doc_type,
  chunk_strategy,
  retrieval_strategy,
  created_by,
  created_at,
  updated_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9
)
RETURNING
  id,
  name,
  description,
  doc_type,
  chunk_strategy,
  retrieval_strategy,
  0::bigint AS document_count,
  0::bigint AS chunk_count,
  created_by,
  created_at,
  updated_at,
  deleted_at
`

type CreateKnowledgeBaseParams struct {
	ID                string             `json:"id"`
	Name              string             `json:"name"`
	Description       string             `json:"description"`
	DocType           string             `json:"doc_type"`
	ChunkStrategy     []byte             `json:"chunk_strategy"`
	RetrievalStrategy []byte             `json:"retrieval_strategy"`
	CreatedBy         string             `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type CreateKnowledgeBaseRow struct {
	ID                string             `json:"id"`
	Name              string             `json:"name"`
	Description       string             `json:"description"`
	DocType           string             `json:"doc_type"`
	ChunkStrategy     []byte             `json:"chunk_strategy"`
	RetrievalStrategy []byte             `json:"retrieval_strategy"`
	DocumentCount     int64              `json:"document_count"`
	ChunkCount        int64              `json:"chunk_count"`
	CreatedBy         string             `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) CreateKnowledgeBase(ctx context.Context, arg CreateKnowledgeBaseParams) (CreateKnowledgeBaseRow, error) {
	row := q.db.QueryRow(ctx, createKnowledgeBase,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.DocType,
		arg.ChunkStrategy,
		arg.RetrievalStrategy,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateKnowledgeBaseRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DocType,
		&i.ChunkStrategy,
		&i.RetrievalStrategy,
		&i.DocumentCount,
		&i.ChunkCount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createProcessingJob = `-- name: CreateProcessingJob :one
INSERT INTO processing_jobs (
  id,
  knowledge_base_id,
  document_id,
  job_type,
  status,
  current_stage,
  progress_percent,
  message,
  error_code,
  error_message,
  attempts,
  max_attempts,
  parser_config_id,
  parser_config_snapshot,
  started_at,
  finished_at,
  created_at,
  updated_at
) VALUES (
  $1,
  $2,
  NULLIF($3, ''),
  $4,
  $5,
  NULLIF($6, ''),
  0,
  NULLIF($7, ''),
  NULL,
  NULL,
  0,
  $8,
  NULLIF($9, ''),
  $10,
  NULL,
  NULL,
  $11,
  $12
)
RETURNING
  id,
  knowledge_base_id,
  document_id,
  job_type,
  status,
  current_stage,
  progress_percent,
  message,
  error_code,
  error_message,
  attempts,
  max_attempts,
  parser_config_id,
  parser_config_snapshot,
  started_at,
  finished_at,
  created_at,
  updated_at
`

type CreateProcessingJobParams struct {
	ID                   string             `json:"id"`
	KnowledgeBaseID      string             `json:"knowledge_base_id"`
	DocumentID           interface{}        `json:"document_id"`
	JobType              string             `json:"job_type"`
	Status               string             `json:"status"`
	CurrentStage         interface{}        `json:"current_stage"`
	Message              interface{}        `json:"message"`
	MaxAttempts          int32              `json:"max_attempts"`
	ParserConfigID       interface{}        `json:"parser_config_id"`
	ParserConfigSnapshot []byte             `json:"parser_config_snapshot"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateProcessingJob(ctx context.Context, arg CreateProcessingJobParams) (ProcessingJob, error) {
	row := q.db.QueryRow(ctx, createProcessingJob,
		arg.ID,
		arg.KnowledgeBaseID,
		arg.DocumentID,
		arg.JobType,
		arg.Status,
		arg.CurrentStage,
		arg.Message,
		arg.MaxAttempts,
		arg.ParserConfigID,
		arg.ParserConfigSnapshot,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ProcessingJob
	err := row.Scan(
		&i.ID,
		&i.KnowledgeBaseID,
		&i.DocumentID,
		&i.JobType,
		&i.Status,
		&i.CurrentStage,
		&i.ProgressPercent,
		&i.Message,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ParserConfigID,
		&i.ParserConfigSnapshot,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeletedDocumentKnowledgeBaseID = `-- name: GetDeletedDocumentKnowledgeBaseID :one
SELECT d.knowledge_base_id
FROM knowledge_documents d
JOIN knowledge_bases kb ON kb.id = d.knowledge_base_id
WHERE d.id = $1
  AND d.deleted_at IS NOT NULL
  AND kb.deleted_at IS NULL
  AND ($2::boolean OR d.created_by = $3 OR kb.created_by = $3)
`

type GetDeletedDocumentKnowledgeBaseIDParams struct {
	ID         string `json:"id"`
	CanReadAll bool   `json:"can_read_all"`
	UserID     string `json:"user_id"`
}

func (q *Queries) GetDeletedDocumentKnowledgeBaseID(ctx context.Context, arg GetDeletedDocumentKnowledgeBaseIDParams) (string, error) {
	row := q.db.QueryRow(ctx, getDeletedDocumentKnowledgeBaseID, arg.ID, arg.CanReadAll, arg.UserID)
	var knowledge_base_id string
	err := row.Scan(&knowledge_base_id)
	return knowledge_base_id, err
}

const getDocument = `-- name: GetDocument :one
SELECT
  d.id,
  d.knowledge_base_id,
  d.file_ref,
  d.name,
  d.content_type,
  d.size_bytes,
  d.status,
  d.error_code,
  d.error_message,
  COALESCE(chunk_counts.chunk_count, 0)::bigint AS chunk_count,
  d.tags,
  d.parser_backend,
  d.current_job_id,
  d.created_by,
  d.created_at,
  d.updated_at,
  d.deleted_at
FROM knowledge_documents d
JOIN knowledge_bases kb ON kb.id = d.knowledge_base_id
LEFT JOIN (
  SELECT document_id, COUNT(*)::bigint AS chunk_count
  FROM document_chunks
  GROUP BY document_id
) chunk_counts ON chunk_counts.document_id = d.id
WHERE d.id = $1
  AND d.deleted_at IS NULL
  AND kb.deleted_at IS NULL
  AND ($2::boolean OR d.created_by = $3 OR kb.created_by = $3)
`

type GetDocumentParams struct {
	ID         string `json:"id"`
	CanReadAll bool   `json:"can_read_all"`
	UserID     string `json:"user_id"`
}

type GetDocumentRow struct {
	ID              string             `json:"id"`
	KnowledgeBaseID string             `json:"knowledge_base_id"`
	FileRef         pgtype.Text        `json:"file_ref"`
	Name            string             `json:"name"`
	ContentType     pgtype.Text        `json:"content_type"`
	SizeBytes       pgtype.Int8        `json:"size_bytes"`
	Status          string             `json:"status"`
	ErrorCode       pgtype.Text        `json:"error_code"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	ChunkCount      int64              `json:"chunk_count"`
	Tags            []byte             `json:"tags"`
	ParserBackend   pgtype.Text        `json:"parser_backend"`
	CurrentJobID    pgtype.Text        `json:"current_job_id"`
	CreatedBy       string             `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (GetDocumentRow, error) {
	row := q.db.QueryRow(ctx, getDocument, arg.ID, arg.CanReadAll, arg.UserID)
	var i GetDocumentRow
	err := row.Scan(
		&i.ID,
		&i.KnowledgeBaseID,
		&i.FileRef,
		&i.Name,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.ChunkCount,
		&i.Tags,
		&i.ParserBackend,
		&i.CurrentJobID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getKnowledgeBase = `-- name: GetKnowledgeBase :one
SELECT
  kb.id,
  kb.name,
  kb.description,
  kb.doc_type,
  kb.chunk_strategy,
  kb.retrieval_strategy,
  COALESCE(doc_counts.document_count, 0)::bigint AS document_count,
  COALESCE(chunk_counts.chunk_count, 0)::bigint AS chunk_count,
  kb.created_by,
  kb.created_at,
  kb.updated_at,
  kb.deleted_at
FROM knowledge_bases kb
LEFT JOIN (
  SELECT knowledge_base_id, COUNT(*)::bigint AS document_count
  FROM knowledge_documents
  WHERE deleted_at IS NULL
  GROUP BY knowledge_base_id
) doc_counts ON doc_counts.knowledge_base_id = kb.id
LEFT JOIN (
  SELECT dc.knowledge_base_id, COUNT(*)::bigint AS chunk_count
  FROM document_chunks dc
  JOIN knowledge_documents d ON d.id = dc.document_id
  WHERE d.deleted_at IS NULL
  GROUP BY dc.knowledge_base_id
) chunk_counts ON chunk_counts.knowledge_base_id = kb.id
WHERE kb.id = $1
  AND kb.deleted_at IS NULL
  AND ($2::boolean OR kb.created_by = $3)
`

type GetKnowledgeBaseParams struct {
	ID         string `json:"id"`
	CanReadAll bool   `json:"can_read_all"`
	UserID     string `json:"user_id"`
}

type GetKnowledgeBaseRow struct {
	ID                string             `json:"id"`
	Name              string             `json:"name"`
	Description       string             `json:"description"`
	DocType           string             `json:"doc_type"`
	ChunkStrategy     []byte             `json:"chunk_strategy"`
	RetrievalStrategy []byte             `json:"retrieval_strategy"`
	DocumentCount     int64              `json:"document_count"`
	ChunkCount        int64              `json:"chunk_count"`
	CreatedBy         string             `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetKnowledgeBase(ctx context.Context, arg GetKnowledgeBaseParams) (GetKnowledgeBaseRow, error) {
	row := q.db.QueryRow(ctx, getKnowledgeBase, arg.ID, arg.CanReadAll, arg.UserID)
	var i GetKnowledgeBaseRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DocType,
		&i.ChunkStrategy,
		&i.RetrievalStrategy,
		&i.DocumentCount,
		&i.ChunkCount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDocumentChunks = `-- name: ListDocumentChunks :many
SELECT
  dc.id,
  dc.knowledge_base_id,
  dc.document_id,
  dc.chunk_index,
  dc.section_path,
  dc.content,
  dc.token_count,
  dc.chunk_type,
  dc.qdrant_point_id,
  dc.embedding_provider,
  dc.embedding_dimension,
  dc.metadata,
  dc.created_at
FROM document_chunks dc
JOIN knowledge_documents d ON d.id = dc.document_id
JOIN knowledge_bases kb ON kb.id = d.knowledge_base_id
WHERE dc.document_id = $1
  AND d.deleted_at IS NULL
  AND kb.deleted_at IS NULL
  AND ($2::boolean OR d.created_by = $3 OR kb.created_by = $3)
ORDER BY dc.chunk_index ASC, dc.id ASC
LIMIT $5 OFFSET $4
`

type ListDocumentChunksParams struct {
	DocumentID  string `json:"document_id"`
	CanReadAll  bool   `json:"can_read_all"`
	UserID      string `json:"user_id"`
	OffsetCount int32  `json:"offset_count"`
	LimitCount  int32  `json:"limit_count"`
}

type ListDocumentChunksRow struct {
	ID                 string             `json:"id"`
	KnowledgeBaseID    string             `json:"knowledge_base_id"`
	DocumentID         string             `json:"document_id"`
	ChunkIndex         int32              `json:"chunk_index"`
	SectionPath        pgtype.Text        `json:"section_path"`
	Content            string             `json:"content"`
	TokenCount         pgtype.Int4        `json:"token_count"`
	ChunkType          pgtype.Text        `json:"chunk_type"`
	QdrantPointID      pgtype.Text        `json:"qdrant_point_id"`
	EmbeddingProvider  pgtype.Text        `json:"embedding_provider"`
	EmbeddingDimension pgtype.Int4        `json:"embedding_dimension"`
	Metadata           []byte             `json:"metadata"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListDocumentChunks(ctx context.Context, arg ListDocumentChunksParams) ([]ListDocumentChunksRow, error) {
	rows, err := q.db.Query(ctx, listDocumentChunks,
		arg.DocumentID,
		arg.CanReadAll,
		arg.UserID,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentChunksRow
	for rows.Next() {
		var i ListDocumentChunksRow
		if err := rows.Scan(
			&i.ID,
			&i.KnowledgeBaseID,
			&i.DocumentID,
			&i.ChunkIndex,
			&i.SectionPath,
			&i.Content,
			&i.TokenCount,
			&i.ChunkType,
			&i.QdrantPointID,
			&i.EmbeddingProvider,
			&i.EmbeddingDimension,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsByKnowledgeBase = `-- name: ListDocumentsByKnowledgeBase :many
SELECT
  d.id,
  d.knowledge_base_id,
  d.file_ref,
  d.name,
  d.content_type,
  d.size_bytes,
  d.status,
  d.error_code,
  d.error_message,
  COALESCE(chunk_counts.chunk_count, 0)::bigint AS chunk_count,
  d.tags,
  d.parser_backend,
  d.current_job_id,
  d.created_by,
  d.created_at,
  d.updated_at,
  d.deleted_at
FROM knowledge_documents d
JOIN knowledge_bases kb ON kb.id = d.knowledge_base_id
LEFT JOIN (
  SELECT document_id, COUNT(*)::bigint AS chunk_count
  FROM document_chunks
  GROUP BY document_id
) chunk_counts ON chunk_counts.document_id = d.id
WHERE d.knowledge_base_id = $1
  AND d.deleted_at IS NULL
  AND kb.deleted_at IS NULL
  AND ($2::boolean OR d.created_by = $3 OR kb.created_by = $3)
  AND ($4::text = '' OR d.status = $4)
ORDER BY d.created_at DESC, d.id DESC
LIMIT $6 OFFSET $5
`

type ListDocumentsByKnowledgeBaseParams struct {
	KnowledgeBaseID string `json:"knowledge_base_id"`
	CanReadAll      bool   `json:"can_read_all"`
	UserID          string `json:"user_id"`
	Status          string `json:"status"`
	OffsetCount     int32  `json:"offset_count"`
	LimitCount      int32  `json:"limit_count"`
}

type ListDocumentsByKnowledgeBaseRow struct {
	ID              string             `json:"id"`
	KnowledgeBaseID string             `json:"knowledge_base_id"`
	FileRef         pgtype.Text        `json:"file_ref"`
	Name            string             `json:"name"`
	ContentType     pgtype.Text        `json:"content_type"`
	SizeBytes       pgtype.Int8        `json:"size_bytes"`
	Status          string             `json:"status"`
	ErrorCode       pgtype.Text        `json:"error_code"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	ChunkCount      int64              `json:"chunk_count"`
	Tags            []byte             `json:"tags"`
	ParserBackend   pgtype.Text        `json:"parser_backend"`
	CurrentJobID    pgtype.Text        `json:"current_job_id"`
	CreatedBy       string             `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListDocumentsByKnowledgeBase(ctx context.Context, arg ListDocumentsByKnowledgeBaseParams) ([]ListDocumentsByKnowledgeBaseRow, error) {
	rows, err := q.db.Query(ctx, listDocumentsByKnowledgeBase,
		arg.KnowledgeBaseID,
		arg.CanReadAll,
		arg.UserID,
		arg.Status,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsByKnowledgeBaseRow
	for rows.Next() {
		var i ListDocumentsByKnowledgeBaseRow
		if err := rows.Scan(
			&i.ID,
			&i.KnowledgeBaseID,
			&i.FileRef,
			&i.Name,
			&i.ContentType,
			&i.SizeBytes,
			&i.Status,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.ChunkCount,
			&i.Tags,
			&i.ParserBackend,
			&i.CurrentJobID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKnowledgeBases = `-- name: ListKnowledgeBases :many
SELECT
  kb.id,
  kb.name,
  kb.description,
  kb.doc_type,
  kb.chunk_strategy,
  kb.retrieval_strategy,
  COALESCE(doc_counts.document_count, 0)::bigint AS document_count,
  COALESCE(chunk_counts.chunk_count, 0)::bigint AS chunk_count,
  kb.created_by,
  kb.created_at,
  kb.updated_at,
  kb.deleted_at
FROM knowledge_bases kb
LEFT JOIN (
  SELECT knowledge_base_id, COUNT(*)::bigint AS document_count
  FROM knowledge_documents
  WHERE deleted_at IS NULL
  GROUP BY knowledge_base_id
) doc_counts ON doc_counts.knowledge_base_id = kb.id
LEFT JOIN (
  SELECT dc.knowledge_base_id, COUNT(*)::bigint AS chunk_count
  FROM document_chunks dc
  JOIN knowledge_documents d ON d.id = dc.document_id
  WHERE d.deleted_at IS NULL
  GROUP BY dc.knowledge_base_id
) chunk_counts ON chunk_counts.knowledge_base_id = kb.id
WHERE kb.deleted_at IS NULL
  AND ($1::boolean OR kb.created_by = $2)
ORDER BY kb.created_at DESC, kb.id DESC
LIMIT $4 OFFSET $3
`

type ListKnowledgeBasesParams struct {
	CanReadAll  bool   `json:"can_read_all"`
	UserID      string `json:"user_id"`
	OffsetCount int32  `json:"offset_count"`
	LimitCount  int32  `json:"limit_count"`
}

type ListKnowledgeBasesRow struct {
	ID                string             `json:"id"`
	Name              string             `json:"name"`
	Description       string             `json:"description"`
	DocType           string             `json:"doc_type"`
	ChunkStrategy     []byte             `json:"chunk_strategy"`
	RetrievalStrategy []byte             `json:"retrieval_strategy"`
	DocumentCount     int64              `json:"document_count"`
	ChunkCount        int64              `json:"chunk_count"`
	CreatedBy         string             `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListKnowledgeBases(ctx context.Context, arg ListKnowledgeBasesParams) ([]ListKnowledgeBasesRow, error) {
	rows, err := q.db.Query(ctx, listKnowledgeBases,
		arg.CanReadAll,
		arg.UserID,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKnowledgeBasesRow
	for rows.Next() {
		var i ListKnowledgeBasesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DocType,
			&i.ChunkStrategy,
			&i.RetrievalStrategy,
			&i.DocumentCount,
			&i.ChunkCount,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDocumentDeleted = `-- name: MarkDocumentDeleted :execrows
UPDATE knowledge_documents d
SET
  deleted_at = $1,
  updated_at = $1,
  current_job_id = $2
FROM knowledge_bases kb
WHERE d.id = $3
  AND kb.id = d.knowledge_base_id
  AND d.deleted_at IS NULL
  AND kb.deleted_at IS NULL
  AND ($4::boolean OR d.created_by = $5 OR kb.created_by = $5)
`

type MarkDocumentDeletedParams struct {
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	CleanupJobID pgtype.Text        `json:"cleanup_job_id"`
	ID           string             `json:"id"`
	CanReadAll   bool               `json:"can_read_all"`
	UserID       string             `json:"user_id"`
}

func (q *Queries) MarkDocumentDeleted(ctx context.Context, arg MarkDocumentDeletedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDocumentDeleted,
		arg.DeletedAt,
		arg.CleanupJobID,
		arg.ID,
		arg.CanReadAll,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markDocumentFailed = `-- name: MarkDocumentFailed :execrows
UPDATE knowledge_documents
SET
  status = 'failed',
  error_code = NULLIF($1, ''),
  error_message = NULLIF($2, ''),
  updated_at = $3
WHERE id = $4
  AND deleted_at IS NULL
`

type MarkDocumentFailedParams struct {
	ErrorCode    interface{}        `json:"error_code"`
	ErrorMessage interface{}        `json:"error_message"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ID           string             `json:"id"`
}

func (q *Queries) MarkDocumentFailed(ctx context.Context, arg MarkDocumentFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDocumentFailed,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markDocumentsDeletedByKnowledgeBase = `-- name: MarkDocumentsDeletedByKnowledgeBase :exec
UPDATE knowledge_documents
SET deleted_at = $1, updated_at = $1
WHERE knowledge_base_id = $2
  AND deleted_at IS NULL
`

type MarkDocumentsDeletedByKnowledgeBaseParams struct {
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	KnowledgeBaseID string             `json:"knowledge_base_id"`
}

func (q *Queries) MarkDocumentsDeletedByKnowledgeBase(ctx context.Context, arg MarkDocumentsDeletedByKnowledgeBaseParams) error {
	_, err := q.db.Exec(ctx, markDocumentsDeletedByKnowledgeBase, arg.DeletedAt, arg.KnowledgeBaseID)
	return err
}

const markKnowledgeBaseDeleted = `-- name: MarkKnowledgeBaseDeleted :execrows
UPDATE knowledge_bases
SET deleted_at = $1, updated_at = $1
WHERE id = $2
  AND deleted_at IS NULL
  AND ($3::boolean OR created_by = $4)
`

type MarkKnowledgeBaseDeletedParams struct {
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	ID         string             `json:"id"`
	CanReadAll bool               `json:"can_read_all"`
	UserID     string             `json:"user_id"`
}

func (q *Queries) MarkKnowledgeBaseDeleted(ctx context.Context, arg MarkKnowledgeBaseDeletedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markKnowledgeBaseDeleted,
		arg.DeletedAt,
		arg.ID,
		arg.CanReadAll,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markProcessingJobFailed = `-- name: MarkProcessingJobFailed :execrows
UPDATE processing_jobs
SET
  status = 'failed',
  error_code = NULLIF($1, ''),
  error_message = NULLIF($2, ''),
  finished_at = $3,
  updated_at = $3
WHERE id = $4
`

type MarkProcessingJobFailedParams struct {
	ErrorCode    interface{}        `json:"error_code"`
	ErrorMessage interface{}        `json:"error_message"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	ID           string             `json:"id"`
}

func (q *Queries) MarkProcessingJobFailed(ctx context.Context, arg MarkProcessingJobFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markProcessingJobFailed,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.FinishedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDocumentTags = `-- name: UpdateDocumentTags :execrows
UPDATE knowledge_documents d
SET
  tags = $1,
  updated_at = $2
FROM knowledge_bases kb
WHERE d.id = $3
  AND kb.id = d.knowledge_base_id
  AND d.deleted_at IS NULL
  AND kb.deleted_at IS NULL
  AND ($4::boolean OR d.created_by = $5 OR kb.created_by = $5)
`

type UpdateDocumentTagsParams struct {
	Tags       []byte             `json:"tags"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ID         string             `json:"id"`
	CanReadAll bool               `json:"can_read_all"`
	UserID     string             `json:"user_id"`
}

func (q *Queries) UpdateDocumentTags(ctx context.Context, arg UpdateDocumentTagsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDocumentTags,
		arg.Tags,
		arg.UpdatedAt,
		arg.ID,
		arg.CanReadAll,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateKnowledgeBase = `-- name: UpdateKnowledgeBase :execrows
UPDATE knowledge_bases
SET
  name = $1,
  description = $2,
  doc_type = $3,
  chunk_strategy = $4,
  retrieval_strategy = $5,
  updated_at = $6
WHERE id = $7
  AND deleted_at IS NULL
  AND ($8::boolean OR created_by = $9)
`

type UpdateKnowledgeBaseParams struct {
	Name              string             `json:"name"`
	Description       string             `json:"description"`
	DocType           string             `json:"doc_type"`
	ChunkStrategy     []byte             `json:"chunk_strategy"`
	RetrievalStrategy []byte             `json:"retrieval_strategy"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ID                string             `json:"id"`
	CanReadAll        bool               `json:"can_read_all"`
	UserID            string             `json:"user_id"`
}

func (q *Queries) UpdateKnowledgeBase(ctx context.Context, arg UpdateKnowledgeBaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateKnowledgeBase,
		arg.Name,
		arg.Description,
		arg.DocType,
		arg.ChunkStrategy,
		arg.RetrievalStrategy,
		arg.UpdatedAt,
		arg.ID,
		arg.CanReadAll,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
