ARG GOOSE_VERSION=v3.27.1

FROM golang:1.25-alpine AS build

ARG GOOSE_VERSION
ENV GOPROXY=https://goproxy.cn,direct

RUN apk add --no-cache git \
    && go install github.com/pressly/goose/v3/cmd/goose@${GOOSE_VERSION}

FROM alpine:3.21

RUN apk add --no-cache ca-certificates
COPY --from=build /go/bin/goose /usr/local/bin/goose

WORKDIR /migrations
ENTRYPOINT ["goose"]
