// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: settings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deactivateAllLLMConfigs = `-- name: DeactivateAllLLMConfigs :exec
UPDATE llm_config_versions
SET is_active = false
WHERE is_active = true
`

func (q *Queries) DeactivateAllLLMConfigs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deactivateAllLLMConfigs)
	return err
}

const deactivateAllQAConfigs = `-- name: DeactivateAllQAConfigs :exec
UPDATE qa_config_versions
SET is_active = false
WHERE is_active = true
`

func (q *Queries) DeactivateAllQAConfigs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deactivateAllQAConfigs)
	return err
}

const deleteMCPServer = `-- name: DeleteMCPServer :execrows
DELETE FROM mcp_servers
WHERE id = $1::uuid
`

func (q *Queries) DeleteMCPServer(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMCPServer, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveLLMConfig = `-- name: GetActiveLLMConfig :one
SELECT
    id::text,
    provider,
    COALESCE(profile_id, '') AS profile_id,
    COALESCE(api_endpoint, '') AS api_endpoint,
    api_key_encrypted,
    COALESCE(api_key_last4, '') AS api_key_last4,
    token_header,
    model_name,
    timeout_seconds,
    temperature,
    max_tokens
FROM llm_config_versions
WHERE is_active = true
ORDER BY version_no DESC
LIMIT 1
`

type GetActiveLLMConfigRow struct {
	ID              string         `json:"id"`
	Provider        string         `json:"provider"`
	ProfileID       string         `json:"profile_id"`
	ApiEndpoint     string         `json:"api_endpoint"`
	ApiKeyEncrypted []byte         `json:"api_key_encrypted"`
	ApiKeyLast4     string         `json:"api_key_last4"`
	TokenHeader     string         `json:"token_header"`
	ModelName       string         `json:"model_name"`
	TimeoutSeconds  int32          `json:"timeout_seconds"`
	Temperature     pgtype.Numeric `json:"temperature"`
	MaxTokens       int32          `json:"max_tokens"`
}

func (q *Queries) GetActiveLLMConfig(ctx context.Context) (GetActiveLLMConfigRow, error) {
	row := q.db.QueryRow(ctx, getActiveLLMConfig)
	var i GetActiveLLMConfigRow
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProfileID,
		&i.ApiEndpoint,
		&i.ApiKeyEncrypted,
		&i.ApiKeyLast4,
		&i.TokenHeader,
		&i.ModelName,
		&i.TimeoutSeconds,
		&i.Temperature,
		&i.MaxTokens,
	)
	return i, err
}

const getActiveQAConfig = `-- name: GetActiveQAConfig :one
SELECT
    id::text,
    top_k,
    similarity_threshold,
    use_rerank,
    COALESCE(rerank_threshold, 0.5)::float8 AS rerank_threshold,
    COALESCE(rerank_top_n, 3)::integer AS rerank_top_n
FROM qa_config_versions
WHERE is_active = true
ORDER BY version_no DESC
LIMIT 1
`

type GetActiveQAConfigRow struct {
	ID                  string         `json:"id"`
	TopK                int32          `json:"top_k"`
	SimilarityThreshold pgtype.Numeric `json:"similarity_threshold"`
	UseRerank           bool           `json:"use_rerank"`
	RerankThreshold     float64        `json:"rerank_threshold"`
	RerankTopN          int32          `json:"rerank_top_n"`
}

func (q *Queries) GetActiveQAConfig(ctx context.Context) (GetActiveQAConfigRow, error) {
	row := q.db.QueryRow(ctx, getActiveQAConfig)
	var i GetActiveQAConfigRow
	err := row.Scan(
		&i.ID,
		&i.TopK,
		&i.SimilarityThreshold,
		&i.UseRerank,
		&i.RerankThreshold,
		&i.RerankTopN,
	)
	return i, err
}

const getMCPServer = `-- name: GetMCPServer :one
SELECT
    id::text,
    alias,
    display_name,
    transport,
    COALESCE(command, '') AS command,
    args_json,
    COALESCE(endpoint_url, '') AS endpoint_url,
    token_encrypted,
    COALESCE(token_last4, '') AS token_last4,
    token_header,
    tool_timeout_seconds,
    enabled,
    sort_order,
    tool_count,
    last_connected_at,
    COALESCE(last_error, '') AS last_error,
    created_by_user_id,
    created_at,
    updated_at
FROM mcp_servers
WHERE id = $1::uuid
`

type GetMCPServerRow struct {
	ID                 string             `json:"id"`
	Alias              string             `json:"alias"`
	DisplayName        string             `json:"display_name"`
	Transport          string             `json:"transport"`
	Command            string             `json:"command"`
	ArgsJson           []byte             `json:"args_json"`
	EndpointUrl        string             `json:"endpoint_url"`
	TokenEncrypted     []byte             `json:"token_encrypted"`
	TokenLast4         string             `json:"token_last4"`
	TokenHeader        string             `json:"token_header"`
	ToolTimeoutSeconds int32              `json:"tool_timeout_seconds"`
	Enabled            bool               `json:"enabled"`
	SortOrder          int32              `json:"sort_order"`
	ToolCount          int32              `json:"tool_count"`
	LastConnectedAt    pgtype.Timestamptz `json:"last_connected_at"`
	LastError          string             `json:"last_error"`
	CreatedByUserID    string             `json:"created_by_user_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetMCPServer(ctx context.Context, id pgtype.UUID) (GetMCPServerRow, error) {
	row := q.db.QueryRow(ctx, getMCPServer, id)
	var i GetMCPServerRow
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.DisplayName,
		&i.Transport,
		&i.Command,
		&i.ArgsJson,
		&i.EndpointUrl,
		&i.TokenEncrypted,
		&i.TokenLast4,
		&i.TokenHeader,
		&i.ToolTimeoutSeconds,
		&i.Enabled,
		&i.SortOrder,
		&i.ToolCount,
		&i.LastConnectedAt,
		&i.LastError,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRuntimeSetting = `-- name: GetRuntimeSetting :one
SELECT value
FROM qa_runtime_settings
WHERE key = $1
`

func (q *Queries) GetRuntimeSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRow(ctx, getRuntimeSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO admin_audit_logs (
    external_user_id,
    action,
    target_type,
    target_id,
    before_data,
    after_data,
    request_id
) VALUES (
    $1,
    $2,
    $3,
    NULLIF($4, ''),
    $5,
    $6,
    NULLIF($7, '')
)
`

type InsertAuditLogParams struct {
	ExternalUserID string      `json:"external_user_id"`
	Action         string      `json:"action"`
	TargetType     string      `json:"target_type"`
	TargetID       interface{} `json:"target_id"`
	BeforeData     []byte      `json:"before_data"`
	AfterData      []byte      `json:"after_data"`
	RequestID      interface{} `json:"request_id"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ExternalUserID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.BeforeData,
		arg.AfterData,
		arg.RequestID,
	)
	return err
}

const insertLLMConfigVersion = `-- name: InsertLLMConfigVersion :exec
INSERT INTO llm_config_versions (
    version_no,
    provider,
    profile_id,
    api_endpoint,
    api_key_encrypted,
    api_key_last4,
    token_header,
    model_name,
    timeout_seconds,
    temperature,
    max_tokens,
    is_active,
    created_by_user_id
) VALUES (
    $1,
    'direct',
    NULL,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    true,
    $10
)
`

type InsertLLMConfigVersionParams struct {
	VersionNo       int32          `json:"version_no"`
	ApiEndpoint     pgtype.Text    `json:"api_endpoint"`
	ApiKeyEncrypted []byte         `json:"api_key_encrypted"`
	ApiKeyLast4     pgtype.Text    `json:"api_key_last4"`
	TokenHeader     string         `json:"token_header"`
	ModelName       string         `json:"model_name"`
	TimeoutSeconds  int32          `json:"timeout_seconds"`
	Temperature     pgtype.Numeric `json:"temperature"`
	MaxTokens       int32          `json:"max_tokens"`
	CreatedByUserID string         `json:"created_by_user_id"`
}

func (q *Queries) InsertLLMConfigVersion(ctx context.Context, arg InsertLLMConfigVersionParams) error {
	_, err := q.db.Exec(ctx, insertLLMConfigVersion,
		arg.VersionNo,
		arg.ApiEndpoint,
		arg.ApiKeyEncrypted,
		arg.ApiKeyLast4,
		arg.TokenHeader,
		arg.ModelName,
		arg.TimeoutSeconds,
		arg.Temperature,
		arg.MaxTokens,
		arg.CreatedByUserID,
	)
	return err
}

const insertMCPServer = `-- name: InsertMCPServer :one
INSERT INTO mcp_servers (
    alias,
    display_name,
    transport,
    command,
    args_json,
    endpoint_url,
    token_encrypted,
    token_last4,
    token_header,
    tool_timeout_seconds,
    enabled,
    sort_order,
    created_by_user_id
) VALUES (
    $1,
    $2,
    $3,
    NULLIF($4, ''),
    $5,
    NULLIF($6, ''),
    $7,
    NULLIF($8, ''),
    $9,
    $10,
    $11,
    $12,
    $13
)
RETURNING id::text, created_at, updated_at
`

type InsertMCPServerParams struct {
	Alias              string      `json:"alias"`
	DisplayName        string      `json:"display_name"`
	Transport          string      `json:"transport"`
	Command            interface{} `json:"command"`
	ArgsJson           []byte      `json:"args_json"`
	EndpointUrl        interface{} `json:"endpoint_url"`
	TokenEncrypted     []byte      `json:"token_encrypted"`
	TokenLast4         interface{} `json:"token_last4"`
	TokenHeader        string      `json:"token_header"`
	ToolTimeoutSeconds int32       `json:"tool_timeout_seconds"`
	Enabled            bool        `json:"enabled"`
	SortOrder          int32       `json:"sort_order"`
	CreatedByUserID    string      `json:"created_by_user_id"`
}

type InsertMCPServerRow struct {
	ID        string             `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertMCPServer(ctx context.Context, arg InsertMCPServerParams) (InsertMCPServerRow, error) {
	row := q.db.QueryRow(ctx, insertMCPServer,
		arg.Alias,
		arg.DisplayName,
		arg.Transport,
		arg.Command,
		arg.ArgsJson,
		arg.EndpointUrl,
		arg.TokenEncrypted,
		arg.TokenLast4,
		arg.TokenHeader,
		arg.ToolTimeoutSeconds,
		arg.Enabled,
		arg.SortOrder,
		arg.CreatedByUserID,
	)
	var i InsertMCPServerRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const insertQAConfigKnowledgeBase = `-- name: InsertQAConfigKnowledgeBase :exec
INSERT INTO qa_config_knowledge_bases (config_id, external_kb_id, sort_order)
VALUES ($1::uuid, $2, $3)
`

type InsertQAConfigKnowledgeBaseParams struct {
	ConfigID     pgtype.UUID `json:"config_id"`
	ExternalKbID string      `json:"external_kb_id"`
	SortOrder    int32       `json:"sort_order"`
}

func (q *Queries) InsertQAConfigKnowledgeBase(ctx context.Context, arg InsertQAConfigKnowledgeBaseParams) error {
	_, err := q.db.Exec(ctx, insertQAConfigKnowledgeBase, arg.ConfigID, arg.ExternalKbID, arg.SortOrder)
	return err
}

const insertQAConfigVersion = `-- name: InsertQAConfigVersion :one
INSERT INTO qa_config_versions (
    version_no,
    top_k,
    similarity_threshold,
    use_rerank,
    rerank_threshold,
    rerank_top_n,
    is_active,
    created_by_user_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    true,
    $7
)
RETURNING id::text
`

type InsertQAConfigVersionParams struct {
	VersionNo           int32          `json:"version_no"`
	TopK                int32          `json:"top_k"`
	SimilarityThreshold pgtype.Numeric `json:"similarity_threshold"`
	UseRerank           bool           `json:"use_rerank"`
	RerankThreshold     pgtype.Numeric `json:"rerank_threshold"`
	RerankTopN          pgtype.Int4    `json:"rerank_top_n"`
	CreatedByUserID     string         `json:"created_by_user_id"`
}

func (q *Queries) InsertQAConfigVersion(ctx context.Context, arg InsertQAConfigVersionParams) (string, error) {
	row := q.db.QueryRow(ctx, insertQAConfigVersion,
		arg.VersionNo,
		arg.TopK,
		arg.SimilarityThreshold,
		arg.UseRerank,
		arg.RerankThreshold,
		arg.RerankTopN,
		arg.CreatedByUserID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listMCPServers = `-- name: ListMCPServers :many
SELECT
    id::text,
    alias,
    display_name,
    transport,
    COALESCE(command, '') AS command,
    args_json,
    COALESCE(endpoint_url, '') AS endpoint_url,
    token_encrypted,
    COALESCE(token_last4, '') AS token_last4,
    token_header,
    tool_timeout_seconds,
    enabled,
    sort_order,
    tool_count,
    last_connected_at,
    COALESCE(last_error, '') AS last_error,
    created_by_user_id,
    created_at,
    updated_at
FROM mcp_servers
ORDER BY sort_order, alias
`

type ListMCPServersRow struct {
	ID                 string             `json:"id"`
	Alias              string             `json:"alias"`
	DisplayName        string             `json:"display_name"`
	Transport          string             `json:"transport"`
	Command            string             `json:"command"`
	ArgsJson           []byte             `json:"args_json"`
	EndpointUrl        string             `json:"endpoint_url"`
	TokenEncrypted     []byte             `json:"token_encrypted"`
	TokenLast4         string             `json:"token_last4"`
	TokenHeader        string             `json:"token_header"`
	ToolTimeoutSeconds int32              `json:"tool_timeout_seconds"`
	Enabled            bool               `json:"enabled"`
	SortOrder          int32              `json:"sort_order"`
	ToolCount          int32              `json:"tool_count"`
	LastConnectedAt    pgtype.Timestamptz `json:"last_connected_at"`
	LastError          string             `json:"last_error"`
	CreatedByUserID    string             `json:"created_by_user_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListMCPServers(ctx context.Context) ([]ListMCPServersRow, error) {
	rows, err := q.db.Query(ctx, listMCPServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMCPServersRow
	for rows.Next() {
		var i ListMCPServersRow
		if err := rows.Scan(
			&i.ID,
			&i.Alias,
			&i.DisplayName,
			&i.Transport,
			&i.Command,
			&i.ArgsJson,
			&i.EndpointUrl,
			&i.TokenEncrypted,
			&i.TokenLast4,
			&i.TokenHeader,
			&i.ToolTimeoutSeconds,
			&i.Enabled,
			&i.SortOrder,
			&i.ToolCount,
			&i.LastConnectedAt,
			&i.LastError,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQAConfigKnowledgeBaseIDs = `-- name: ListQAConfigKnowledgeBaseIDs :many
SELECT external_kb_id
FROM qa_config_knowledge_bases
WHERE config_id = $1::uuid
ORDER BY sort_order, external_kb_id
`

func (q *Queries) ListQAConfigKnowledgeBaseIDs(ctx context.Context, configID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listQAConfigKnowledgeBaseIDs, configID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var external_kb_id string
		if err := rows.Scan(&external_kb_id); err != nil {
			return nil, err
		}
		items = append(items, external_kb_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLLMConfigVersions = `-- name: LockLLMConfigVersions :exec
LOCK TABLE llm_config_versions IN EXCLUSIVE MODE
`

func (q *Queries) LockLLMConfigVersions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockLLMConfigVersions)
	return err
}

const lockQAConfigVersions = `-- name: LockQAConfigVersions :exec
LOCK TABLE qa_config_versions IN EXCLUSIVE MODE
`

func (q *Queries) LockQAConfigVersions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockQAConfigVersions)
	return err
}

const nextLLMConfigVersionNo = `-- name: NextLLMConfigVersionNo :one
SELECT COALESCE(MAX(version_no), 0) + 1::integer AS version_no
FROM llm_config_versions
`

func (q *Queries) NextLLMConfigVersionNo(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, nextLLMConfigVersionNo)
	var version_no int32
	err := row.Scan(&version_no)
	return version_no, err
}

const nextQAConfigVersionNo = `-- name: NextQAConfigVersionNo :one
SELECT COALESCE(MAX(version_no), 0) + 1::integer AS version_no
FROM qa_config_versions
`

func (q *Queries) NextQAConfigVersionNo(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, nextQAConfigVersionNo)
	var version_no int32
	err := row.Scan(&version_no)
	return version_no, err
}

const updateMCPConnectionStatus = `-- name: UpdateMCPConnectionStatus :exec
UPDATE mcp_servers
SET
    tool_count = $1,
    last_connected_at = $2,
    last_error = NULLIF($3, ''),
    updated_at = now()
WHERE id = $4::uuid
`

type UpdateMCPConnectionStatusParams struct {
	ToolCount       int32              `json:"tool_count"`
	LastConnectedAt pgtype.Timestamptz `json:"last_connected_at"`
	LastError       interface{}        `json:"last_error"`
	ID              pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateMCPConnectionStatus(ctx context.Context, arg UpdateMCPConnectionStatusParams) error {
	_, err := q.db.Exec(ctx, updateMCPConnectionStatus,
		arg.ToolCount,
		arg.LastConnectedAt,
		arg.LastError,
		arg.ID,
	)
	return err
}

const updateMCPServer = `-- name: UpdateMCPServer :one
UPDATE mcp_servers
SET
    display_name = $1,
    transport = $2,
    command = NULLIF($3, ''),
    args_json = $4,
    endpoint_url = NULLIF($5, ''),
    token_encrypted = $6,
    token_last4 = NULLIF($7, ''),
    token_header = $8,
    tool_timeout_seconds = $9,
    enabled = $10,
    sort_order = $11,
    updated_at = now()
WHERE id = $12::uuid
RETURNING updated_at
`

type UpdateMCPServerParams struct {
	DisplayName        string      `json:"display_name"`
	Transport          string      `json:"transport"`
	Command            interface{} `json:"command"`
	ArgsJson           []byte      `json:"args_json"`
	EndpointUrl        interface{} `json:"endpoint_url"`
	TokenEncrypted     []byte      `json:"token_encrypted"`
	TokenLast4         interface{} `json:"token_last4"`
	TokenHeader        string      `json:"token_header"`
	ToolTimeoutSeconds int32       `json:"tool_timeout_seconds"`
	Enabled            bool        `json:"enabled"`
	SortOrder          int32       `json:"sort_order"`
	ID                 pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateMCPServer(ctx context.Context, arg UpdateMCPServerParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, updateMCPServer,
		arg.DisplayName,
		arg.Transport,
		arg.Command,
		arg.ArgsJson,
		arg.EndpointUrl,
		arg.TokenEncrypted,
		arg.TokenLast4,
		arg.TokenHeader,
		arg.ToolTimeoutSeconds,
		arg.Enabled,
		arg.SortOrder,
		arg.ID,
	)
	var updated_at pgtype.Timestamptz
	err := row.Scan(&updated_at)
	return updated_at, err
}

const upsertRuntimeSetting = `-- name: UpsertRuntimeSetting :exec
INSERT INTO qa_runtime_settings (key, value, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value, updated_at = now()
`

type UpsertRuntimeSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertRuntimeSetting(ctx context.Context, arg UpsertRuntimeSettingParams) error {
	_, err := q.db.Exec(ctx, upsertRuntimeSetting, arg.Key, arg.Value)
	return err
}
